---
roles:
  - name: lordoftheflies.ansible_role_java
    source: https://galaxy.ansible.com
  - name: lordoftheflies.ansible_role_python
    source: https://galaxy.ansible.com
  - name: lordoftheflies.ansible_role_nodejs
    source: https://galaxy.ansible.com
  - name: lordoftheflies.ansible_role_vagrant
    source: https://galaxy.ansible.com

collections:
#  - name: lordoftheflies.basic_roles
#    source: https://galaxy.ansible.com
  - name: lordoftheflies.ansible_collection_freeipa
    version: '*'
    source: https://galaxy.ansible.com
#  - name: lordoftheflies.sdlc_roles
#    source: https://galaxy.ansible.com
#  - name: lordoftheflies.soho_roles
#    source: https://galaxy.ansible.com